version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-unique-set_server_1
      APP_PORT: 80

  server:
    image: impranshu/unique-game:v1@sha256:a1347e044dba208489af840f9bf4191b71cd28c5b9ec9ceca1c9a722da319a3d
    volumes:
      - ${APP_DATA_DIR}/data/src:/app/src
