version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-dash_server_1
      APP_PORT: 80

  server:
    image: impranshu/dash:v1
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: on-failure
