version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-stick-walker_server_1
      APP_PORT: 80

  server:
    image: impranshu/stick-walker:v1@sha256:7459c14c71a4291d255b2a939242295f72697f5e8a9a9454a9a5a9ac0865dd9f
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: on-failure
