version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-save-baloon_server_1
      APP_PORT: 80

  server:
    image: impranshu/save-baloon:v1@sha256:d53a54786c9b52bb6853327d68ef1ef1687dffcc7e68125c21d512e6e3d3c856
    volumes:
      - ${APP_DATA_DIR}/data/src:/app/src
